#include "nsISupports.idl"

[scriptable, uuid(341fd800-4690-11dd-ae16-0800200c9a66)]
interface iSimpleMecab : nsISupports {
    readonly attribute AString version;	/*means lib version, not dictionary version*/
    readonly attribute AString error;
    readonly attribute AString dictionaryInfo;	/* The mecab_dictionary_info_t members joined in one string formatted as "filename=XXX;charset=YYY;..." */
	boolean loadLib(in AString libPath);
	boolean createTagger(in AString arguments);
	boolean parse(in AString text);
	boolean next(out AString surface, out AString feature, out unsigned long length);
	/* TODO: return all the nodes strings in one call? nsIArray or nsIMutableArray can be used if the xpidl [array] modifier doesn't work well.
	boolean getAll([array] out AString surfaces, [array] out AString features, [array] out unsigned long lengths);*/	
};
